### ISSUE TITLE
ECONNRESET and Crash

### ISSUE THREAD

**Issue by insideGen** [timonreinhard/wemo-client#29]
```
wemo-client Error on http.request.req: Timed out!
wemo-client Error on http.request.req: { [Error: socket hang up] code: 'ECONNRESET' }
wemo-client Error on http.request.req: Timed out!
TypeError: Cannot read property 'root' of null
TypeError: Cannot read property 'root' of null
  at /home/pi/meshblu-wemo-motion/node_modules/wemo-client/index.js:35:24
  at Parser.<anonymous> (/home/pi/meshblu-wemo-motion/node_modules/wemo-client/node_modules/xml2js/lib/xml2js.js:484:18)
  at Parser.emit (events.js:95:17)
  at Parser.exports.Parser.Parser.parseString (/home/pi/meshblu-wemo-motion/node_modules/wemo-client/node_modules/xml2js/lib/xml2js.js:494:16)
  at Parser.parseString (/home/pi/meshblu-wemo-motion/node_modules/wemo-client/node_modules/xml2js/lib/xml2js.js:7:59)
  at Object.exports.parseString (/home/pi/meshblu-wemo-motion/node_modules/wemo-client/node_modules/xml2js/lib/xml2js.js:535:19)
  at IncomingMessage.<anonymous> (/home/pi/meshblu-wemo-motion/node_modules/wemo-client/client.js:63:14)
  at IncomingMessage.emit (events.js:117:20)
  at _stream_readable.js:929:16
  at process._tickCallback (node.js:419:13)
```

**Comment by timonreinhard** [comment]
Thanks for reporting. I'm currently investigating if this issue was introduced with 0.6.4 or is related to a recent Wemo firmware update. Which version of wemo-client are you on?

**Comment by insideGen** [comment]
v0.6.4

**Comment by timonreinhard** [comment]
Please upgrade to 0.6.5 which resolves this issue.

**Comment by insideGen** [comment]
Okay, thanks. I will try that tomorrow.
This error has took two days before to appear.
I'll keep you informed.

**Comment by timonreinhard** [comment]
Thanks. Please reopen in case you spot this again after updating.
