### ISSUE TITLE
Examples crash with Error: addMembership EHOSTUNREACH

### ISSUE THREAD

**Issue by m-altmeyer** [timonreinhard/wemo-client#46]
First of all thank you so much for this great work! I just bought an Insight switch and wanted to try out your API but was not able to get the examples running. I tried 'insight.js' but always got the following error when calling wemo.discover(...):

```javascript
Error: addMembership EHOSTUNREACH
    at exports._errnoException (util.js:1026:11)
    at Socket.addMembership (dgram.js:508:11)
    at addMembership ([***]\wemo-test\node_modules\node
-ssdp\lib\index.js:177:19)
    at Socket.onSocketListening ([***]\wemo-test\node_m
odules\node-ssdp\lib\index.js:173:5)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at startListening (dgram.js:121:10)
    at dgram.js:228:7
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```
The insight switch is in the same network as the PC running the example. Moreover I am able to control the switch using the official Wemo App. Do you have any idea what might cause this issue?

Thank you so much and all the best,
Max

**Comment by timonreinhard** [comment]
Seems related to node-ssdp. Which OS are you running?

**Comment by m-altmeyer** [comment]
I am running on Windows 10

**Comment by timonreinhard** [comment]
Can you please try upgrading `node-ssdp` to the latest 2.9.0 (e.g. by bumping the version in `package.json` and then running `npm update`)? If that still doesn't help, I suppose you create an issue for [node-ssdp](https://github.com/diversario/node-ssdp).

**Comment by m-altmeyer** [comment]
Thank you for your fast reply. I updated to 2.9.0 but still get the same error. I'll raise an issue at node-ssdp and I think this one can be closed.

**Comment by timonreinhard** [comment]
Requires diversario/node-ssdp#66

**Comment by jeffrey-cochran** [comment]
If you're on Windows, you'll almost certainly need to install IIS. I had the same issue, and this fixed it. You can find a brief guide on installing it [here](https://www.howtogeek.com/112455/how-to-install-iis-8-on-windows-8/). 

I had the same issue and installing IIS fixed it. Tip of the hat to Fullstack React authors, whose book I remembered saying something to this effect.
